cargo-features = ["per-package-target"]

[package]
name = "uprogs"
description = "octox user programs"
authors = ["Hayato Ohhashi <o8@vmm.dev>"]
edition = "2021"
version.workspace = true
license.workspace = true
repository.workspace = true
forced-target = "riscv64gc-unknown-none-elf"

[lib]
name = "ulib"
path = "lib/lib.rs"
test = false

[[bin]]
name = "_cat"
path = "bin/cat.rs"
test = false

[[bin]]
name = "_echo"
path = "bin/echo.rs"
test = false

[[bin]]
name = "_grep"
path = "bin/grep.rs"
test = false

[[bin]]
name = "_init"
path = "bin/init.rs"
test = false

[[bin]]
name = "_initcode"
path = "bin/initcode.rs"
test = false

[[bin]]
name = "_kill"
path = "bin/kill.rs"
test = false

[[bin]]
name = "_ln"
path = "bin/ln.rs"
test = false

[[bin]]
name = "_ls"
path = "bin/ls.rs"
test = false

[[bin]]
name = "_mkdir"
path = "bin/mkdir.rs"
test = false

[[bin]]
name = "_rm"
path = "bin/rm.rs"
test = false

[[bin]]
name = "_sh"
path = "bin/sh.rs"
test = false

[[bin]]
name = "_wc"
path = "bin/wc.rs"
test = false

[[bin]]
name = "_head"
path = "bin/head.rs"
test = false

[[bin]]
name = "_clear"
path = "bin/clear.rs"
test = false

[[bin]]
name = "_sleep"
path = "bin/sleep.rs"
test = false

[[bin]]
name = "_touch"
path = "bin/touch.rs"
test = false

[[bin]]
name = "_jell"
path = "bin/jell.rs"
test = false

[dependencies]
libkernel = { workspace = true, default-features = false }

[build-dependencies]
libkernel = { workspace = true, default-features = false }
